### ISSUE TITLE
Scrolling page when using Guide tour

### ISSUE THREAD

**Issue by iranapex** [Dani3lSun/apex-plugin-guidedtour#2]
### Expected behavior

As a follower, when scroll on items they are going behind the breadcrumb. See below picture please.
![image](https://cloud.githubusercontent.com/assets/13412866/13407520/bb6d496a-df20-11e5-9ff5-52e24e2f0f2f.png)

**Comment by Dani3lSun** [comment]
Hi @iranapex 
isnt´t that expected behavior? Guided tour should stay on top shouldn´t it?
If you would like to have the guided tour region lower you could try to add some css to alter the z-index:

```
.shepherd-element.shepherd-theme-dark {
    z-index: 1;
}
```

Set z-index to a value that´s lower than that of breadcrumb bar...

**Comment by Dani3lSun** [comment]
I haven't heared something from you, so I will close the issue now...If you have something to that topic just post, I will open it again...
